[package]
name = "orgtools-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.16"
orgtools = { path = "../orgtools-lib" }
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.18"
chrono = "0.4.38"
anyhow = "1.0.88"
